VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hey, kid! What do you think you're\n"
    .string "doing here?\p"
    .string "You won't live long in combat!\n"
    .string "Not with your puny power!\p"
    .string "I tell you, kid, electric POKéMON\n"
    .string "saved me during the war!\p"
    .string "They zapped my enemies into\n"
    .string "paralysis!\p"
    .string "The same as I'll do to you!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "A little word of advice, kid!\p"
    .string "Electricity is sure powerful!\p"
    .string "But, it's useless against GROUND-\n"
    .string "type POKéMON!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "The THUNDERBADGE cranks up your\n"
    .string "POKéMON's SPEED!\p"
    .string "It also lets your POKéMON FLY\n"
    .string "lightning-quick anytime, kid!\p"
    .string "You're special, kid!\n"
    .string "Take this!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} received TM34\n"
    .string "from LT. SURGE.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 contains SHOCK WAVE!\p"
    .string "Teach it to an ELECTRIC POKéMON!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Yo, kid, make room in your BAG!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Now that's a shocker!\p"
    .string "You're the real deal, kid!\p"
    .string "Fine, then, take the THUNDERBADGE!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "When I was in the Army, LT. SURGE\n"
    .string "was my strict CO.\p"
    .string "He was a hard taskmaster.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Stop!\n"
    .string "You're very good!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "LT. SURGE is tough!\p"
    .string "He was a pilot in the Army and\n"
    .string "saved his POKéMON's life in the war.\p"
    .string "They've been partners ever since!$"

VermilionCity_Gym_Text_BailyIntro::
    .string "I'm a lightweight, but I'm good\n"
    .string "with electricity!\p"
    .string "That's why I joined this GYM.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Fried!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Okay, I'll talk!\p"
    .string "LT. SURGE's POKéMON know\n"
    .string "THUNDERBOLT and THUNDER WAVE!\p"
    .string "You better have some\n"
    .string "PARALYZE HEAL ready!$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "This is no place for kids!\n"
    .string "Not even if you're good!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Wow!\n"
    .string "Surprised me!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE used to have all these\n"
    .string "locks and traps in the GYM.\p"
    .string "But he got rid of them recently.\n"
    .string "Said real trainers don't need gimmicks!\p"
    .string "Though he kept the trash cans\n"
    .string "for some reason...$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "LT. SURGE has a nickname.\p"
    .string "People refer to him as the\n"
    .string "Lightning American!\p"
    .string "He's an expert on electric\n"
    .string "POKéMON.\p"
    .string "BIRD/WATER-type POKéMON match\n"
    .string "poorly against the ELECTRIC type.\p"
    .string "Beware of paralysis, too.\p"
    .string "LT. SURGE is ready and waiting!\n"
    .string "Give him a real shock!$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Whew!\n"
    .string "That match was electric!$"

VermilionCity_Gym_Text_GymStatue::
    .string "VERMILION POKéMON GYM\n"
    .string "LEADER: LT. SURGE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "VERMILION POKéMON GYM\n"
    .string "LEADER: LT. SURGE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "It's just trash!\n"
    .string "Why does Lt. Surge keep garbage\l"
    .string "cans in his Gym anyway?$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! There's a switch under the\n"
    .string "trash! Turn it on!\p"
    .string "The first electric lock opened!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "The second electric lock opened!\n"
    .string "The motorized door opened!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Nope!\n"
    .string "There's only trash here.\p"
    .string "Hey!\n"
    .string "The electric locks were reset!$"

